#ifndef TOOL_ID_FIELDS_H
#define TOOL_ID_FIELDS_H

// NOTE: 複数行にしたかったが、フォーマットすると纏まってしまう
#define TOOL_ID_FIELDS() \
    SAMPLE_0, SAMPLE_1, SAMPLE_2, SAMPLE_3, HTTP_REQUEST, COMMAND_GENERATION, IMAGE_RESIZE, \
        IMAGE_ROTATION, IMAGE_SPLIT, IMAGE_TRANSPARENT, IMAGE_TRIM, IMAGE_COMBINE, \
        PHRASE_GENERATION

#endif // TOOL_ID_FIELDS_H
